name: Basic CI
on: [push]


jobs:
  linuxBuild:
    name: Ubuntu - ${{ matrix.swift-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        swift-version: [5.1.3, 5.1.5, 5.2]
        os: [ubuntu-18.04]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Download Swift ${{ matrix.swift-version }}
      run: wget -q https://swift.org/builds/swift-${{ matrix.swift-version }}-release/ubuntu1804/swift-${{ matrix.swift-version }}-RELEASE/swift-${{ matrix.swift-version }}-RELEASE-ubuntu18.04.tar.gz
    - name: Extract Swift ${{ matrix.swift-version }}
      run: tar xzf swift-${{ matrix.swift-version }}-RELEASE-ubuntu18.04.tar.gz
    - name: Add Path
      run: echo "::add-path::$GITHUB_WORKSPACE/swift-${{ matrix.swift-version }}-RELEASE-ubuntu18.04/usr/bin"      
    - name: Swift Package Information
      run: |
        swift --version
        swift package show-dependencies
    - name: Build
      run: swift build --build-tests
    - name: Test
      run: swift test

  macOSBuild:
    name: Xcode
    runs-on: macos-latest
        
    steps:
      - name: Report Xcode Version
        run: xcode-select -p
      - name: Checkout
        uses: actions/checkout@v1
      - name: Swift Package Information
        run: |
          swift --version
          swift package show-dependencies
      - name: Build
        run: swift build --build-tests
      - name: Test
        run: swift test
      - name: Swiftlint
        run: |
          brew install swiftlint
          swiftlint
