name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04
    env:
      SWIFT_PATH: ${HOME}/swift/bin/swift
    strategy:
      max-parallel: 2
      matrix:
        swift-version: [4.1.3, 5.0.3, 5.1]
    
    steps:
    - name: Install Swift
      env:
        SWIFT_VERSION: ${{ matrix.swift-version }}
      run: |
        mkdir ${HOME}/swift
        curl https://swift.org/builds/swift-${SWIFT_VERSION}-release/ubuntu1604/swift-${SWIFT_VERSION}-RELEASE/swift-${SWIFT_VERSION}-RELEASE-ubuntu16.04.tar.gz -s | tar -xz -C ${HOME}/swift --strip-components=2
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build & Test
      run: |
        export PATH="${PATH}:${HOME}/swift/bin/"
        swift package reset
        swift package show-dependencies
        swift build
        swift test

  macOSBuild:
    runs-on: macOS-latest
    strategy:
      max-parallel: 1
      matrix:
        xcode-version: [11.0, 10.3]
        
    steps:
      - name: Configure Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode-version }}.app/
          xcode-select -v
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build & Test
        run: |
          swift package reset
          swift package show-dependencies
          swift build
          swift test
