name: Basic CI
on: [push]


jobs:
  linuxBuild:
    name: Swift ${{ matrix.swift-version }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        swift-version: [5.0.3, 5.1.1]
        os: [ubuntu-18.04]
    
    steps:
    - name: Install Swift
      uses: YOCKOW/Action-setup-swift@master
      with:
          swift-version: ${{ matrix.swift-version }}
    - name: Checkout
      uses: actions/checkout@v1
    - name: Swift Package Information
      run: |
        swift --version
        swift package show-dependencies
    - name: Build
      run: swift build --build-tests
    - name: Test
      run: swift test

  macOSBuild:
    name: macOS - Xcode ${{ matrix.xcode-version }}
    runs-on: macOS-latest
    strategy:
      matrix:
        xcode-version: [11.0]
        
    steps:
      - name: Configure Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode-version }}.app/
          xcode-select -p
      - name: Checkout
        uses: actions/checkout@v1
      - name: Swift Package Information
        run: |
          swift --version
          swift package show-dependencies
      - name: Build
        run: swift build --build-tests
      - name: Test
        run: swift test
      - name: Swiftlint
        run: |
          brew install swiftlint
          swiftlint
