name: Basic CI
on: [push]


jobs:
  linuxBuild:
    name: Ubuntu - ${{ matrix.swift-version }}
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        swift-version: [5.1.5, 5.5.2]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install Swift
      uses: YOCKOW/Action-setup-swift@v1
      with:
          swift-version: ${{ matrix.swift-version }}  
    - name: Swift Package Information
      run: |
        swift --version
        swift package show-dependencies
    - name: Build
      run: swift build --build-tests
    - name: Test
      run: swift test

  macOSBuild:
    name: Xcode
    runs-on: macos-latest
        
    steps:
      - name: Report Xcode Version
        run: xcode-select -p
      - name: Checkout
        uses: actions/checkout@v1
      - name: Swift Package Information
        run: |
          swift --version
          swift package show-dependencies
      - name: Build
        run: swift build --build-tests
      - name: Test
        run: swift test
      - name: Swiftlint
        run: |
          brew install swiftlint
          swiftlint
