name: Full CI
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  linuxBuild:
    name: Ubuntu - ${{ matrix.swift-version }}
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        swift-version: [5.1.5, 5.5.2]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Cache Swift ${{ matrix.swift-version }}
      uses: actions/cache@v1
      id: cache-swift
      with:
        path: ${{ github.workspace }}/swift-${{ matrix.swift-version }}-RELEASE-ubuntu18.04
        key: ${{ runner.os }}-swift-${{ matrix.swift-version }}
    - name: Download Swift ${{ matrix.swift-version }}
      if: steps.cache-swift.outputs.cache-hit != 'true'
      run: wget -q https://swift.org/builds/swift-${{ matrix.swift-version }}-release/ubuntu1804/swift-${{ matrix.swift-version }}-RELEASE/swift-${{ matrix.swift-version }}-RELEASE-ubuntu18.04.tar.gz
    - name: Extract Swift ${{ matrix.swift-version }}
      if: steps.cache-swift.outputs.cache-hit != 'true'
      run: tar xzf swift-${{ matrix.swift-version }}-RELEASE-ubuntu18.04.tar.gz
    - name: Add Path
      run: echo "::add-path::$GITHUB_WORKSPACE/swift-${{ matrix.swift-version }}-RELEASE-ubuntu18.04/usr/bin"      
    - name: Swift Package Information
      run: |
        swift --version
        swift package show-dependencies
    - name: Build
      run: swift build --build-tests
    - name: Test
      run: swift test

  swiftLintChecks:
    name: Swiftlint
    runs-on: macos-latest
    strategy:
      max-parallel: 1
        
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Swiftlint
        run: |
          brew install swiftlint
          swiftlint --strict
