name: Full CI
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  linuxBuild:
    name: Ubuntu - ${{ matrix.swift-version }}
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        swift-version: [5.1.5, 5.5.2]
    
    steps:
    - name: Install Swift
      uses: YOCKOW/Action-setup-swift@v1
      with:
          swift-version: ${{ matrix.swift-version }}
    - name: Checkout
      uses: actions/checkout@v1
    - name: Swift Package Information
      run: |
        swift --version
        swift package show-dependencies
    - name: Build
      run: swift build --build-tests
    - name: Test
      run: swift test
    - name: SwiftLint
      uses: norio-nomura/action-swiftlint@3.2.1
      env:
          WORKING_DIRECTORY: Sources
