name: Full CI
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  push:
    branches:
      - master

jobs:
  raspbianStretchBuild:
    name: ARM Stretch - Swift ${{ matrix.swift-version }}
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        swift-version: [5.0.3, 5.1.1]
    steps:
      - name: Checkout
        uses: actions/checkout@v1.0.0
      - name: Build in QEMU
        uses: uraimo/run-on-arch-action@v1.0.5
        id: runcmd
        with:
          architecture: armv6
          distribution: stretch
          run: |
            apt update
            apt install -y clang-3.8 libncurses-dev libxml2-dev libicu-dev libcurl4-nss-dev
            apt install -y curl git
            update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-3.8 100
            update-alternatives --install /usr/bin/clang clang /usr/bin/clang-3.8 100
            curl -o swift-${{ matrix.swift-version }}.tgz -L https://github.com/uraimo/buildSwiftOnARM/releases/download/${{ matrix.swift-version }}/swift-${{ matrix.swift-version }}-armv6-RPi0123-RaspbianStretch.tgz
            tar xzf swift-${{ matrix.swift-version }}.tgz
            ./usr/bin/swift build -j 1
            ./usr/bin/swift test

  swiftLintChecks:
    name: Swiftlint
    runs-on: macOS-latest
    strategy:
      max-parallel: 1
        
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Swiftlint
        run: |
          brew install swiftlint
          swiftlint --strict
